-- ============================================
-- ADD SAMPLE FLIGHT DATA TO BRIDGE55
-- ============================================

-- Insert sample flight listings
INSERT INTO listings (
  title,
  description,
  service_type,
  type,
  property_type,
  location,
  city,
  country,
  country_code,
  price,
  price_unit,
  currency,
  rating,
  review_count,
  active,
  verified,
  featured,
  service_data,
  metadata,
  max_guests,
  bedrooms,
  bathrooms,
  price_per_night,
  created_at,
  updated_at
) VALUES

-- Flight 1: Nairobi to Addis Ababa
(
  'Nairobi (NBO) to Addis Ababa (ADD)',
  'Direct flight with Ethiopian Airlines, 2h 15m duration',
  'flight',
  'flight',
  'flight',
  'Nairobi to Addis Ababa',
  'Nairobi',
  'Kenya',
  'KE',
  180.00,
  'per_person',
  'USD',
  4.6,
  234,
  TRUE,
  TRUE,
  TRUE,
  jsonb_build_object(
    'airline', 'Ethiopian Airlines',
    'flight_number', 'ET308',
    'departure_city', 'Nairobi',
    'departure_airport', 'Jomo Kenyatta International (NBO)',
    'arrival_city', 'Addis Ababa',
    'arrival_airport', 'Bole International (ADD)',
    'departure_time', '10:30',
    'arrival_time', '12:45',
    'duration_hours', 2,
    'duration_minutes', 15,
    'stops', 0,
    'aircraft', 'Boeing 737-800',
    'cabin_class', 'Economy',
    'baggage_allowance', '23kg',
    'meals_included', true,
    'refundable', false,
    'available_seats', 12
  ),
  jsonb_build_object(
    'route_type', 'international',
    'booking_class', 'economy'
  ),
  0, 0, 0, 0,
  NOW(),
  NOW()
),

-- Flight 2: Nairobi to Lagos
(
  'Nairobi (NBO) to Lagos (LOS)',
  'Direct flight with Kenya Airways, 5h 30m duration',
  'flight',
  'flight',
  'flight',
  'Nairobi to Lagos',
  'Nairobi',
  'Kenya',
  'KE',
  420.00,
  'per_person',
  'USD',
  4.8,
  189,
  TRUE,
  TRUE,
  TRUE,
  jsonb_build_object(
    'airline', 'Kenya Airways',
    'flight_number', 'KQ536',
    'departure_city', 'Nairobi',
    'departure_airport', 'Jomo Kenyatta International (NBO)',
    'arrival_city', 'Lagos',
    'arrival_airport', 'Murtala Muhammed International (LOS)',
    'departure_time', '14:00',
    'arrival_time', '19:30',
    'duration_hours', 5,
    'duration_minutes', 30,
    'stops', 0,
    'aircraft', 'Boeing 787 Dreamliner',
    'cabin_class', 'Economy',
    'baggage_allowance', '23kg',
    'meals_included', true,
    'refundable', false,
    'available_seats', 8
  ),
  jsonb_build_object(
    'route_type', 'international',
    'booking_class', 'economy'
  ),
  0, 0, 0, 0,
  NOW(),
  NOW()
),

-- Flight 3: Nairobi to Johannesburg
(
  'Nairobi (NBO) to Johannesburg (JNB)',
  'Direct flight with Kenya Airways, 4h 45m duration',
  'flight',
  'flight',
  'flight',
  'Nairobi to Johannesburg',
  'Nairobi',
  'Kenya',
  'KE',
  350.00,
  'per_person',
  'USD',
  4.7,
  312,
  TRUE,
  TRUE,
  TRUE,
  jsonb_build_object(
    'airline', 'Kenya Airways',
    'flight_number', 'KQ762',
    'departure_city', 'Nairobi',
    'departure_airport', 'Jomo Kenyatta International (NBO)',
    'arrival_city', 'Johannesburg',
    'arrival_airport', 'O.R. Tambo International (JNB)',
    'departure_time', '09:00',
    'arrival_time', '13:45',
    'duration_hours', 4,
    'duration_minutes', 45,
    'stops', 0,
    'aircraft', 'Boeing 787 Dreamliner',
    'cabin_class', 'Economy',
    'baggage_allowance', '23kg',
    'meals_included', true,
    'refundable', false,
    'available_seats', 15
  ),
  jsonb_build_object(
    'route_type', 'international',
    'booking_class', 'economy'
  ),
  0, 0, 0, 0,
  NOW(),
  NOW()
),

-- Flight 4: Nairobi to Dubai
(
  'Nairobi (NBO) to Dubai (DXB)',
  'Direct flight with Emirates, 4h 50m duration',
  'flight',
  'flight',
  'flight',
  'Nairobi to Dubai',
  'Nairobi',
  'Kenya',
  'KE',
  450.00,
  'per_person',
  'USD',
  4.9,
  567,
  TRUE,
  TRUE,
  TRUE,
  jsonb_build_object(
    'airline', 'Emirates',
    'flight_number', 'EK720',
    'departure_city', 'Nairobi',
    'departure_airport', 'Jomo Kenyatta International (NBO)',
    'arrival_city', 'Dubai',
    'arrival_airport', 'Dubai International (DXB)',
    'departure_time', '23:45',
    'arrival_time', '04:35',
    'duration_hours', 4,
    'duration_minutes', 50,
    'stops', 0,
    'aircraft', 'Boeing 777-300ER',
    'cabin_class', 'Economy',
    'baggage_allowance', '30kg',
    'meals_included', true,
    'refundable', false,
    'available_seats', 20
  ),
  jsonb_build_object(
    'route_type', 'international',
    'booking_class', 'economy'
  ),
  0, 0, 0, 0,
  NOW(),
  NOW()
),

-- Flight 5: Mombasa to Nairobi
(
  'Mombasa (MBA) to Nairobi (NBO)',
  'Domestic flight with Kenya Airways, 1h 10m duration',
  'flight',
  'flight',
  'flight',
  'Mombasa to Nairobi',
  'Mombasa',
  'Kenya',
  'KE',
  85.00,
  'per_person',
  'USD',
  4.5,
  892,
  TRUE,
  TRUE,
  FALSE,
  jsonb_build_object(
    'airline', 'Kenya Airways',
    'flight_number', 'KQ612',
    'departure_city', 'Mombasa',
    'departure_airport', 'Moi International (MBA)',
    'arrival_city', 'Nairobi',
    'arrival_airport', 'Jomo Kenyatta International (NBO)',
    'departure_time', '07:00',
    'arrival_time', '08:10',
    'duration_hours', 1,
    'duration_minutes', 10,
    'stops', 0,
    'aircraft', 'Embraer E190',
    'cabin_class', 'Economy',
    'baggage_allowance', '15kg',
    'meals_included', false,
    'refundable', true,
    'available_seats', 25
  ),
  jsonb_build_object(
    'route_type', 'domestic',
    'booking_class', 'economy'
  ),
  0, 0, 0, 0,
  NOW(),
  NOW()
),

-- Flight 6: Accra to Lagos
(
  'Accra (ACC) to Lagos (LOS)',
  'Regional flight with Africa World Airlines, 1h 15m duration',
  'flight',
  'flight',
  'flight',
  'Accra to Lagos',
  'Accra',
  'Ghana',
  'GH',
  95.00,
  'per_person',
  'USD',
  4.4,
  156,
  TRUE,
  TRUE,
  FALSE,
  jsonb_build_object(
    'airline', 'Africa World Airlines',
    'flight_number', 'AW150',
    'departure_city', 'Accra',
    'departure_airport', 'Kotoka International (ACC)',
    'arrival_city', 'Lagos',
    'arrival_airport', 'Murtala Muhammed International (LOS)',
    'departure_time', '11:30',
    'arrival_time', '12:45',
    'duration_hours', 1,
    'duration_minutes', 15,
    'stops', 0,
    'aircraft', 'ERJ-145',
    'cabin_class', 'Economy',
    'baggage_allowance', '20kg',
    'meals_included', true,
    'refundable', false,
    'available_seats', 10
  ),
  jsonb_build_object(
    'route_type', 'regional',
    'booking_class', 'economy'
  ),
  0, 0, 0, 0,
  NOW(),
  NOW()
);

-- Verify insertion
SELECT 
  'Flight data added successfully!' AS status,
  COUNT(*) FILTER (WHERE service_type = 'flight') AS total_flights,
  COUNT(*) FILTER (WHERE service_type = 'flight' AND featured = TRUE) AS featured_flights
FROM listings;
