-- ============================================
-- ADD NAIROBI HOTELS TO BRIDGE55
-- ============================================

INSERT INTO listings (
  title,
  description,
  property_type,
  type,
  city,
  country,
  country_code,
  address,
  latitude,
  longitude,
  max_guests,
  bedrooms,
  bathrooms,
  price_per_night,
  currency,
  images,
  amenities,
  is_active,
  rating,
  review_count,
  active,
  verified,
  featured,
  created_at,
  updated_at
) VALUES

-- Hotel 1: Safari Park Hotel Nairobi
(
  'Safari Park Hotel & Casino',
  'Luxury hotel with casino, outdoor pool, and lush gardens in the heart of Nairobi',
  'hotel',
  'hotel',
  'Nairobi',
  'Kenya',
  'KE',
  'Thika Road, Nairobi',
  -1.2194,
  36.8925,
  4,
  2,
  2,
  250.00,
  'USD',
  ARRAY['https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80'],
  ARRAY['Pool', 'Casino', 'Restaurant', 'WiFi', 'Gym', 'Spa', 'Parking'],
  TRUE,
  4.7,
  342,
  TRUE,
  TRUE,
  TRUE,
  NOW(),
  NOW()
),

-- Hotel 2: The Boma Nairobi
(
  'The Boma Nairobi',
  'Boutique hotel with rooftop terrace, located in the trendy Westlands area',
  'hotel',
  'hotel',
  'Nairobi',
  'Kenya',
  'KE',
  'Muthangari Drive, Westlands, Nairobi',
  -1.2674,
  36.8046,
  2,
  1,
  1,
  180.00,
  'USD',
  ARRAY['https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&q=80'],
  ARRAY['Rooftop Bar', 'Restaurant', 'WiFi', 'Airport Shuttle', 'Garden'],
  TRUE,
  4.6,
  198,
  TRUE,
  TRUE,
  TRUE,
  NOW(),
  NOW()
),

-- Hotel 3: Fairview Hotel Nairobi
(
  'Fairview Hotel',
  'Historic garden hotel offering peaceful retreat in the city center',
  'hotel',
  'hotel',
  'Nairobi',
  'Kenya',
  'KE',
  'Bishops Road, Nairobi',
  -1.2764,
  36.8155,
  4,
  2,
  2,
  160.00,
  'USD',
  ARRAY['https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&q=80'],
  ARRAY['Garden', 'Pool', 'Restaurant', 'WiFi', 'Conference Rooms', 'Parking'],
  TRUE,
  4.5,
  267,
  TRUE,
  TRUE,
  FALSE,
  NOW(),
  NOW()
),

-- Hotel 4: Nairobi Serena Hotel
(
  'Nairobi Serena Hotel',
  '5-star luxury hotel in the heart of Nairobi CBD with stunning city views',
  'hotel',
  'hotel',
  'Nairobi',
  'Kenya',
  'KE',
  'Kenyatta Avenue, Nairobi',
  -1.2845,
  36.8215,
  2,
  1,
  1,
  320.00,
  'USD',
  ARRAY['https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80'],
  ARRAY['Pool', 'Spa', 'Restaurant', 'Bar', 'WiFi', 'Gym', 'Business Center', 'Concierge'],
  TRUE,
  4.8,
  456,
  TRUE,
  TRUE,
  TRUE,
  NOW(),
  NOW()
),

-- Apartment 1: Kilimani Apartments
(
  'Modern Kilimani Apartment',
  'Fully furnished 2-bedroom apartment in quiet Kilimani neighborhood',
  'apartment',
  'apartment',
  'Nairobi',
  'Kenya',
  'KE',
  'Argwings Kodhek Road, Kilimani, Nairobi',
  -1.2921,
  36.7833,
  4,
  2,
  2,
  120.00,
  'USD',
  ARRAY['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80'],
  ARRAY['Kitchen', 'WiFi', 'Parking', 'Security', 'Balcony', 'Washing Machine'],
  TRUE,
  4.4,
  89,
  TRUE,
  TRUE,
  FALSE,
  NOW(),
  NOW()
),

-- Guesthouse 1: Karen Guesthouse
(
  'Karen Blixen Guesthouse',
  'Charming guesthouse in the upscale Karen suburb, near Giraffe Centre',
  'guesthouse',
  'guesthouse',
  'Nairobi',
  'Kenya',
  'KE',
  'Karen Road, Karen, Nairobi',
  -1.3206,
  36.7073,
  6,
  3,
  3,
  200.00,
  'USD',
  ARRAY['https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800&q=80'],
  ARRAY['Garden', 'WiFi', 'Breakfast Included', 'Parking', 'Pet Friendly', 'Library'],
  TRUE,
  4.9,
  134,
  TRUE,
  TRUE,
  TRUE,
  NOW(),
  NOW()
);

-- Verify insertion
SELECT 
  'Nairobi hotels added successfully!' AS status,
  COUNT(*) FILTER (WHERE city = 'Nairobi') AS nairobi_stays,
  COUNT(*) FILTER (WHERE city = 'Nairobi' AND featured = TRUE) AS featured_nairobi
FROM listings
WHERE type IN ('hotel', 'apartment', 'guesthouse', 'resort', 'villa');

